// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.4
// source: calldata.proto

package calldata

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Calldata wraps the raw data or the data ref in eigenda
type Calldata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Value:
	//
	//	*Calldata_Raw
	//	*Calldata_EigendaRef
	//	*Calldata_Digest
	//	*Calldata_CelestiaRef
	//	*Calldata_AvailRef
	Value isCalldata_Value `protobuf_oneof:"value"`
}

func (x *Calldata) Reset() {
	*x = Calldata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_calldata_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Calldata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Calldata) ProtoMessage() {}

func (x *Calldata) ProtoReflect() protoreflect.Message {
	mi := &file_calldata_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Calldata.ProtoReflect.Descriptor instead.
func (*Calldata) Descriptor() ([]byte, []int) {
	return file_calldata_proto_rawDescGZIP(), []int{0}
}

func (m *Calldata) GetValue() isCalldata_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *Calldata) GetRaw() []byte {
	if x, ok := x.GetValue().(*Calldata_Raw); ok {
		return x.Raw
	}
	return nil
}

func (x *Calldata) GetEigendaRef() *EigenDARef {
	if x, ok := x.GetValue().(*Calldata_EigendaRef); ok {
		return x.EigendaRef
	}
	return nil
}

func (x *Calldata) GetDigest() *Digest {
	if x, ok := x.GetValue().(*Calldata_Digest); ok {
		return x.Digest
	}
	return nil
}

func (x *Calldata) GetCelestiaRef() *CelestiaRef {
	if x, ok := x.GetValue().(*Calldata_CelestiaRef); ok {
		return x.CelestiaRef
	}
	return nil
}

func (x *Calldata) GetAvailRef() *AvailRef {
	if x, ok := x.GetValue().(*Calldata_AvailRef); ok {
		return x.AvailRef
	}
	return nil
}

type isCalldata_Value interface {
	isCalldata_Value()
}

type Calldata_Raw struct {
	Raw []byte `protobuf:"bytes,1,opt,name=raw,proto3,oneof"`
}

type Calldata_EigendaRef struct {
	EigendaRef *EigenDARef `protobuf:"bytes,2,opt,name=eigenda_ref,json=eigendaRef,proto3,oneof"`
}

type Calldata_Digest struct {
	Digest *Digest `protobuf:"bytes,3,opt,name=Digest,proto3,oneof"`
}

type Calldata_CelestiaRef struct {
	CelestiaRef *CelestiaRef `protobuf:"bytes,4,opt,name=celestia_ref,json=celestiaRef,proto3,oneof"`
}

type Calldata_AvailRef struct {
	AvailRef *AvailRef `protobuf:"bytes,5,opt,name=avail_ref,json=availRef,proto3,oneof"`
}

func (*Calldata_Raw) isCalldata_Value() {}

func (*Calldata_EigendaRef) isCalldata_Value() {}

func (*Calldata_Digest) isCalldata_Value() {}

func (*Calldata_CelestiaRef) isCalldata_Value() {}

func (*Calldata_AvailRef) isCalldata_Value() {}

type EigenDARef struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BatchHeaderHash []byte `protobuf:"bytes,1,opt,name=batch_header_hash,json=batchHeaderHash,proto3" json:"batch_header_hash,omitempty"`
	BlobIndex       uint32 `protobuf:"varint,2,opt,name=blob_index,json=blobIndex,proto3" json:"blob_index,omitempty"`
}

func (x *EigenDARef) Reset() {
	*x = EigenDARef{}
	if protoimpl.UnsafeEnabled {
		mi := &file_calldata_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EigenDARef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EigenDARef) ProtoMessage() {}

func (x *EigenDARef) ProtoReflect() protoreflect.Message {
	mi := &file_calldata_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EigenDARef.ProtoReflect.Descriptor instead.
func (*EigenDARef) Descriptor() ([]byte, []int) {
	return file_calldata_proto_rawDescGZIP(), []int{1}
}

func (x *EigenDARef) GetBatchHeaderHash() []byte {
	if x != nil {
		return x.BatchHeaderHash
	}
	return nil
}

func (x *EigenDARef) GetBlobIndex() uint32 {
	if x != nil {
		return x.BlobIndex
	}
	return 0
}

type CelestiaRef struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CelestiaRef) Reset() {
	*x = CelestiaRef{}
	if protoimpl.UnsafeEnabled {
		mi := &file_calldata_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CelestiaRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CelestiaRef) ProtoMessage() {}

func (x *CelestiaRef) ProtoReflect() protoreflect.Message {
	mi := &file_calldata_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CelestiaRef.ProtoReflect.Descriptor instead.
func (*CelestiaRef) Descriptor() ([]byte, []int) {
	return file_calldata_proto_rawDescGZIP(), []int{2}
}

func (x *CelestiaRef) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

type AvailRef struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockHash string `protobuf:"bytes,1,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	Sender    string `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	Nonce     int64  `protobuf:"varint,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
}

func (x *AvailRef) Reset() {
	*x = AvailRef{}
	if protoimpl.UnsafeEnabled {
		mi := &file_calldata_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AvailRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailRef) ProtoMessage() {}

func (x *AvailRef) ProtoReflect() protoreflect.Message {
	mi := &file_calldata_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailRef.ProtoReflect.Descriptor instead.
func (*AvailRef) Descriptor() ([]byte, []int) {
	return file_calldata_proto_rawDescGZIP(), []int{3}
}

func (x *AvailRef) GetBlockHash() string {
	if x != nil {
		return x.BlockHash
	}
	return ""
}

func (x *AvailRef) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *AvailRef) GetNonce() int64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

type Digest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *Digest) Reset() {
	*x = Digest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_calldata_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Digest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Digest) ProtoMessage() {}

func (x *Digest) ProtoReflect() protoreflect.Message {
	mi := &file_calldata_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Digest.ProtoReflect.Descriptor instead.
func (*Digest) Descriptor() ([]byte, []int) {
	return file_calldata_proto_rawDescGZIP(), []int{4}
}

func (x *Digest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_calldata_proto protoreflect.FileDescriptor

var file_calldata_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x63, 0x61, 0x6c, 0x6c, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x64, 0x61, 0x74, 0x61, 0x22, 0xfb, 0x01, 0x0a, 0x08, 0x43,
	0x61, 0x6c, 0x6c, 0x64, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x03, 0x72, 0x61, 0x77, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x03, 0x72, 0x61, 0x77, 0x12, 0x37, 0x0a, 0x0b, 0x65,
	0x69, 0x67, 0x65, 0x6e, 0x64, 0x61, 0x5f, 0x72, 0x65, 0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x63, 0x61, 0x6c, 0x6c, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x45, 0x69, 0x67, 0x65,
	0x6e, 0x44, 0x41, 0x52, 0x65, 0x66, 0x48, 0x00, 0x52, 0x0a, 0x65, 0x69, 0x67, 0x65, 0x6e, 0x64,
	0x61, 0x52, 0x65, 0x66, 0x12, 0x2a, 0x0a, 0x06, 0x44, 0x69, 0x67, 0x65, 0x73, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63, 0x61, 0x6c, 0x6c, 0x64, 0x61, 0x74, 0x61, 0x2e,
	0x44, 0x69, 0x67, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x06, 0x44, 0x69, 0x67, 0x65, 0x73, 0x74,
	0x12, 0x3a, 0x0a, 0x0c, 0x63, 0x65, 0x6c, 0x65, 0x73, 0x74, 0x69, 0x61, 0x5f, 0x72, 0x65, 0x66,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x63, 0x61, 0x6c, 0x6c, 0x64, 0x61, 0x74,
	0x61, 0x2e, 0x43, 0x65, 0x6c, 0x65, 0x73, 0x74, 0x69, 0x61, 0x52, 0x65, 0x66, 0x48, 0x00, 0x52,
	0x0b, 0x63, 0x65, 0x6c, 0x65, 0x73, 0x74, 0x69, 0x61, 0x52, 0x65, 0x66, 0x12, 0x31, 0x0a, 0x09,
	0x61, 0x76, 0x61, 0x69, 0x6c, 0x5f, 0x72, 0x65, 0x66, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x63, 0x61, 0x6c, 0x6c, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x41, 0x76, 0x61, 0x69, 0x6c,
	0x52, 0x65, 0x66, 0x48, 0x00, 0x52, 0x08, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x66, 0x42,
	0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x57, 0x0a, 0x0a, 0x45, 0x69, 0x67, 0x65,
	0x6e, 0x44, 0x41, 0x52, 0x65, 0x66, 0x12, 0x2a, 0x0a, 0x11, 0x62, 0x61, 0x74, 0x63, 0x68, 0x5f,
	0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x0f, 0x62, 0x61, 0x74, 0x63, 0x68, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x48, 0x61,
	0x73, 0x68, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x6c, 0x6f, 0x62, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x62, 0x6c, 0x6f, 0x62, 0x49, 0x6e, 0x64, 0x65,
	0x78, 0x22, 0x1d, 0x0a, 0x0b, 0x43, 0x65, 0x6c, 0x65, 0x73, 0x74, 0x69, 0x61, 0x52, 0x65, 0x66,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x57, 0x0a, 0x08, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x66, 0x12, 0x1d, 0x0a, 0x0a,
	0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x61, 0x73, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x22, 0x22, 0x0a, 0x06, 0x44, 0x69, 0x67,
	0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x42, 0x0d, 0x5a,
	0x0b, 0x70, 0x62, 0x2f, 0x63, 0x61, 0x6c, 0x6c, 0x64, 0x61, 0x74, 0x61, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_calldata_proto_rawDescOnce sync.Once
	file_calldata_proto_rawDescData = file_calldata_proto_rawDesc
)

func file_calldata_proto_rawDescGZIP() []byte {
	file_calldata_proto_rawDescOnce.Do(func() {
		file_calldata_proto_rawDescData = protoimpl.X.CompressGZIP(file_calldata_proto_rawDescData)
	})
	return file_calldata_proto_rawDescData
}

var file_calldata_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_calldata_proto_goTypes = []interface{}{
	(*Calldata)(nil),    // 0: calldata.Calldata
	(*EigenDARef)(nil),  // 1: calldata.EigenDARef
	(*CelestiaRef)(nil), // 2: calldata.CelestiaRef
	(*AvailRef)(nil),    // 3: calldata.AvailRef
	(*Digest)(nil),      // 4: calldata.Digest
}
var file_calldata_proto_depIdxs = []int32{
	1, // 0: calldata.Calldata.eigenda_ref:type_name -> calldata.EigenDARef
	4, // 1: calldata.Calldata.Digest:type_name -> calldata.Digest
	2, // 2: calldata.Calldata.celestia_ref:type_name -> calldata.CelestiaRef
	3, // 3: calldata.Calldata.avail_ref:type_name -> calldata.AvailRef
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_calldata_proto_init() }
func file_calldata_proto_init() {
	if File_calldata_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_calldata_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Calldata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_calldata_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EigenDARef); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_calldata_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CelestiaRef); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_calldata_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AvailRef); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_calldata_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Digest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_calldata_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Calldata_Raw)(nil),
		(*Calldata_EigendaRef)(nil),
		(*Calldata_Digest)(nil),
		(*Calldata_CelestiaRef)(nil),
		(*Calldata_AvailRef)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_calldata_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_calldata_proto_goTypes,
		DependencyIndexes: file_calldata_proto_depIdxs,
		MessageInfos:      file_calldata_proto_msgTypes,
	}.Build()
	File_calldata_proto = out.File
	file_calldata_proto_rawDesc = nil
	file_calldata_proto_goTypes = nil
	file_calldata_proto_depIdxs = nil
}
